config/routes.rb
ToolShare::Application.routes.draw do

  resources :users
  resources :tools
  resources :sessions, only: [:new, :create, :destroy]

  root :to => "static#index"
  match '/signup', :to=> 'users#new'
  match '/signin', :to=> 'sessions#new'
  match '/signout',:to=> 'sessions#destroy', via: :delete
end

app/models/tool.rb
# == Schema Information
#
# Table name: tools
#
#  id         :integer          not null, primary key
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  name       :string(255)
#

class Tool < ActiveRecord::Base

  attr_accessible :name

  validates :name, presence: true

  has_many :userTools
  has_many :users, :through => :userTools
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :integer          not null, primary key
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#  name            :string(255)
#  email           :string(255)
#  password_digest :string(255)
#

class User < ActiveRecord::Base
  # validations
    validates :name, presence: true, length: {maximum: 50}
    VALID_EMAIL_REGEX = / \A          # match start of a string
                        [\w+\-.]+     # at least one word character, plus, hyphen, or dot
                        @             # @ character
                        [a-z\d\-.]+   # at least one letter, digit, hyphen, dot
                        \.            # . character
                        [a-z]+        # at least one letter
                        \z            # match end of string
                        /x            # ignore whitespaces in this regex

    validates :email, presence: true, format: { with: VALID_EMAIL_REGEX }, uniqueness: { case_sensitive: false }
    validates :password, presence: true, length: {minimum: 6}
    validates :password_confirmation, presence: true

  # relationships
    has_many :userTools
    has_many :tools,  :through => :userTools

  # before saves; a callback
    before_save {|user| user.email = email.downcase} # ensures that email is saved in all lowercase
    before_save :create_remember_token

  # accessible attributes (not all of these attributes have DB entries)
    attr_accessible :name, :email, :password, :password_confirmation
    has_secure_password # pulls in needed secure_password.rb toolbox

  private
    def create_remember_token # sets its own remember_token
      self.remember_token = SecureRandom.urlsafe_base64
    end

end

app/models/user_tool.rb
# == Schema Information
#
# Table name: user_tools
#
#  id         :integer          not null, primary key
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  user_id    :integer
#  tool_id    :integer
#

class UserTool < ActiveRecord::Base

  validates :user_id, presence: true
  validates :tool_id, presence: true

  belongs_to :tool
  belongs_to :user

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  include SessionsHelper

  # Force signout to prevent CSRF attacks
  def handle_unverified_request
    sign_out
    super
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end


  def create
    user = User.find_by_email(params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
        # user exists and authenticates
        sign_in user
        redirect_to user
    else
       # user either doesn't exist or doesn't authenticate
      flash.now[:error] = "Invalid email/password combination"
      render 'new'
    end

  end


  def destroy
    sign_out(@user)
    redirect_to root_path
  end

end

app/controllers/static_controller.rb
class StaticController < ApplicationController
  # controller for static pages
  #   - home page

  def index

  end

end

app/controllers/tools_controller.rb
class ToolsController < ApplicationController

  def create
    @tool = Tool.new(params[:tool])
    puts @tool.name
    if @tool.save
     redirect_to '/tools'
    else
     render :new
    end
  end

  def edit
  end

  def index
    @tools = Tool.all
  end

  def show
  end

  def new
    @tool = Tool.new
  end

  def update
  end

#  def destroy
#  end

# def delete
#  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def create
    @user = User.new(params[:user])
    if @user.save
      sign_in @user
      flash[:success] = "Welcome!"
       redirect_to @user
    else
      render 'new'
    end
  end

  def edit
  end

  def index
  end

  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def update
  end

#  def destroy
#  end

# def delete
#  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper


  def sign_in(user)
    cookies.permanent[:remember_token] = user.remember_token
    self.current_user = user     # what is "self" here? Is it a session?
  end

  def current_user=(user) # assignment method
    @current_user = user
  end

  def current_user   # retrieve method
    @current_user ||= User.find_by_remember_token(cookies[:remember_token]) # get user by finding token stored in cookie
    # ||=  is the 'or equals' operator
  end

  def signed_in?
    !current_user.nil? # if current user is not nil then user is signed in
  end

  def sign_out(user)
    self.current_user = nil
    cookies.delete(:remember_token)
  end
end

app/helpers/tool_helper.rb
module ToolHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_header.html.erb
<header>
<ul>
  <li><%= link_to "Home", root_path %></li>
  <li>
    <% if signed_in? %>
        <%= link_to "Sign out", signout_path, method: "delete" %>
    <% else %>
        <%= link_to "Sign in", signin_path %>
    <% end %>
  </li>
</ul>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ToolShare</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

    <%= render 'layouts/header' %>

  <! add flash message >
  <div class="container">
    <% flash.each do |key,value|%>
      <div class="alert alert-<%= key %>"><%= value %> </div>
    <% end %>
  </div>

<%= yield %>

</body>
</html>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
    <div id="error_explanation">
        <div class="alert alert-error">
            The form contains <%= pluralize(@user.errors.count, "error") %>
        </div>

        <ul>
            <% @user.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
        </ul>
    </div>
<%end %>

app/views/tools/index.html.erb
<% @tools.each do |tool| %>
 <%= tool.name %>
 <br>
<% end %>

app/views/tools/new.html.erb
<h1> Add a new tool</h1>
<%= form_for (@tool) do |f|%>
<p>
  <%= f.label :name %>
  <%= f.text_field :name %><br>
  <%= f.submit "Add tool" %>

</p>
<% end  %>

app/views/users/new.html.erb
<h1>Sign up</h1>


<div class="row">
    <div class="span6 offset3">
        <%= form_for(@user) do |f|%>
        <%= render'shared/error_messages' %>

        <%= f.label :name %>
        <%= f.text_field :name %><br>

        <%= f.label :email %>
        <%= f.text_field :email %><br>

        <%= f.label :password %>
        <%= f.password_field :password %><br>

        <%= f.label :password_confirmation, "Confirm" %>
        <%= f.password_field :password_confirmation %><br>

        <%= f.submit "Create Account" %><br>

        <%end%>
    </div>
</div>


<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<h1><%= @user.name %></h1>
<%= @user.email%>